tseloe=10
drobnoe=8.4
stroka="No"
big_netseloe=tseloe*3.5
drobnoe=drobnoe-1
tseloe/drobnoe
big_netseloe/drobnoe
stroka=stroka+"NoNo_YesYesYes"
print(tseloe)
print(drobnoe)
print(big_netseloe)
print(stroka)